# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  rust: circleci/rust@1.6.0

jobs:
  clippy:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - checkout
      - rust/clippy
  format:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - checkout
      - rust/format
  test:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - checkout
      - rust/test
  integration-test:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - checkout
      - run:
          name: Integration Test
          command: |
            cargo test -- --ignored

workflows:
  test:
    jobs:
      - clippy
      - format
      - test
