# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  rust: circleci/rust@1.6.0

jobs:
  clippy:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - checkout
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - rust/clippy
  format:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - checkout
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - rust/format
  test:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - checkout
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - rust/test
  integration-test:
    executor:
      name: rust/default
      tag: 1.58.1
    steps:
      - checkout
      - run:
          name: Select Nightly Rust
          command: |
            rustup default nightly
      - run:
          name: Create Scratch Org
          command: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
            echo $DEVHUB_SFDX_URL > ./DEVHUB_SFDX_URL.txt
            sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a DevHub -d
            source scratch-org.sh
      - run:
          name: Integration Test
          command: |
            source refresh-token.sh
            cargo test -- --ignored
      - run:
          name: Delete Scratch Org
          command: |
            sfdx force:org:delete -u baris

workflows:
  test:
    jobs:
      - clippy
      - format
      - test
      - integration-test
